image: node:18.10.0

stages:
  - build

build:
  stage: build

  script:
    - npm install
    - npm run build

  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/
      - build
  except: # Do not trigger a pipeline when pushing tags
    - tags
